//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KryptonAccessController.International {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KryptonAccessController.International.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Time.
        /// </summary>
        internal static string AccessTime {
            get {
                return ResourceManager.GetString("AccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Info.
        /// </summary>
        internal static string CardInfo {
            get {
                return ResourceManager.GetString("CardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        internal static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contr Relat.
        /// </summary>
        internal static string ControllerRelation {
            get {
                return ResourceManager.GetString("ControllerRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Name.
        /// </summary>
        internal static string DataBaseName {
            get {
                return ResourceManager.GetString("DataBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string DataBaseUserName {
            get {
                return ResourceManager.GetString("DataBaseUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string DataBaseUserPassword {
            get {
                return ResourceManager.GetString("DataBaseUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi Manage.
        /// </summary>
        internal static string DeviceManage {
            get {
                return ResourceManager.GetString("DeviceManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door Unit.
        /// </summary>
        internal static string DoorUnit {
            get {
                return ResourceManager.GetString("DoorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expan Board.
        /// </summary>
        internal static string ExpansionBoard {
            get {
                return ResourceManager.GetString("ExpansionBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailInfo.
        /// </summary>
        internal static string FailInfo {
            get {
                return ResourceManager.GetString("FailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBase Validator.
        /// </summary>
        internal static string FormDataBaseValidatorText {
            get {
                return ResourceManager.GetString("FormDataBaseValidatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string FormLoginText {
            get {
                return ResourceManager.GetString("FormLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessSystem.
        /// </summary>
        internal static string FormMainText {
            get {
                return ResourceManager.GetString("FormMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpRelation {
            get {
                return ResourceManager.GetString("HelpRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        internal static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show the dialog again.
        /// </summary>
        internal static string OnlyOne {
            get {
                return ResourceManager.GetString("OnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Help.
        /// </summary>
        internal static string OpenHelpFile {
            get {
                return ResourceManager.GetString("OpenHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader.
        /// </summary>
        internal static string Reader {
            get {
                return ResourceManager.GetString("Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Rela.
        /// </summary>
        internal static string RecordRelation {
            get {
                return ResourceManager.GetString("RecordRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Manager.
        /// </summary>
        internal static string SystemManager {
            get {
                return ResourceManager.GetString("SystemManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Group.
        /// </summary>
        internal static string TimeGroup {
            get {
                return ResourceManager.GetString("TimeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Rela.
        /// </summary>
        internal static string TimeRelation {
            get {
                return ResourceManager.GetString("TimeRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        internal static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string ToolRelation {
            get {
                return ResourceManager.GetString("ToolRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Psw.
        /// </summary>
        internal static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Relat.
        /// </summary>
        internal static string UserRelation {
            get {
                return ResourceManager.GetString("UserRelation", resourceCulture);
            }
        }
    }
}
